name: GitHub Classroom Autograding
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run GitHub Classroom Autograder
        uses: education/autograding@v1
